deployments:
  k8s:
    kubernetes_manifest: ./kube-deployment.yml
    deployment_type: kubernetes
    kubernetes_default_pod: web
    kubernetes_namespace: k8s
    pipelines:
      - k8s:
          scripts:
            web:
              - echo "#!/bin/sh" > /script.sh
              - echo "ls -la" >> /script.sh
              - chmod a+x /script.sh
              - /script.sh
      - all:
          scripts:
            - ls -la
